version: "3.8"
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - /data/nexus_data:/nexus-data
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3
    ports:
      - 8081:8081
      - 8082:8082

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - nexus
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_SERVER_IDENT_CERT}:/etc/ssl/certs/nginx-server-certificate.crt:ro
      - ${NGINX_SERVER_IDENT_PRIVATE_KEY}:/etc/ssl/certs/nginx-server-certificate.key:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3
    ports:
      - 80:80
      - 443:443
