---
- name: Setup Nexus with Docker on CentOS/RHEL
  hosts: all
  become: true
  vars:
    docker_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
    git_repo: https://github.com/joelckwong/DevSecOps-Servers.git
    nexus_dir: /data/nexus_data

  tasks:
    - name: Ensure umask is set to 022
      ansible.builtin.replace:
        path: /etc/profile
        regexp: '077'
        replace: '022'

    - name: Stop and disable fapolicyd
      ansible.builtin.systemd:
        name: fapolicyd
        state: stopped
        enabled: false

    - name: Add Docker CE repository
      ansible.builtin.command:
        cmd: yum-config-manager --add-repo {{ docker_repo_url }}
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Enable container-tools module
      ansible.builtin.command:
        cmd: dnf -y module enable container-tools 

    - name: Install Docker CE
      ansible.builtin.command:
        cmd: dnf -y install docker-ce --allowerasing

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Clone Git repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: ~/DevSecOps-Servers
        version: master

    - name: Create Nexus data directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ nexus_dir }}"

    - name: Set ownership for Nexus directory
      ansible.builtin.file:
        path: "{{ nexus_dir }}"
        owner: 200
        group: 200
        recurse: yes

    - name: Run docker-compose in Nexus directory
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: ~/DevSecOps-Servers/nexus

    - name: Open port 443 permanently
      ansible.builtin.command: firewall-cmd --permanent --add-port=443/tcp

    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload

    - name: List open ports
      ansible.builtin.command: firewall-cmd --list-ports
      register: firewall_ports

    - name: Show open ports
      ansible.builtin.debug:
        var: firewall_ports.stdout

    - name: Pause for 1 minutes to app start
      ansible.builtin.pause:
        minutes: 1 

    - name: Display Nexus initial admin password
      ansible.builtin.command: docker exec -i nexus cat /nexus-data/admin.password
      register: nexus_password
      changed_when: false

    - name: Show nexus admin password
      ansible.builtin.debug:
        var: nexus_password.stdout
