version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /data/jenkins_home
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - jenkins
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_SERVER_IDENT_CERT}:/etc/ssl/certs/nginx-server-certificate.crt:ro
      - ${NGINX_SERVER_IDENT_KEY}:/etc/ssl/certs/nginx-server-certificate.key:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3
    ports:
      - 80:80
      - 443:443