version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_USER=jenkins
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jenkinsdb
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /data/mariadb:/var/lib/mysql
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /data/jenkins_home:/var/jenkins_home
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - jenkins
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_SERVER_IDENT_CERT}:/etc/ssl/certs/nginx-server-certificate.crt:ro
      - ${NGINX_SERVER_IDENT_PRIVATE_KEY}:/etc/ssl/certs/nginx-server-certificate.key:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: 3
    ports:
      - 80:80
      - 443:443
